CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS measurements (
  id SERIAL PRIMARY KEY,
  device_id TEXT NOT NULL,
  lux DOUBLE PRECISION NOT NULL,
  sun_phase TEXT NOT NULL, 
  solar_angle DOUBLE PRECISION NOT NULL, 
  status TEXT NOT NULL, 
  recommendation TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


